# Generated by Django 5.1.15 on 2026-09-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('ACCOUNT_ACCESS', 'Login & account access'), ('BILLING', 'Billing & payments'), ('BUG', 'Something is broken'), ('PERFORMANCE', 'Slow or unavailable'), ('DATA', 'Incorrect or missing data'), ('SECURITY', 'Security concern'), ('OTHER', 'Something else')], default='OTHER', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketevent',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('STATUS_CHANGED', 'Status changed'), ('PRIORITY_CHANGED', 'Priority changed'), ('CATEGORY_CHANGED', 'Category changed'), ('RESPONSE_ADDED', 'Response added'), ('ATTACHMENT_ADDED', 'Attachment added'), ('TOKEN_ISSUED', 'Token issued'), ('TOKEN_REVOKED', 'Token revoked'), ('EMAIL_SENT', 'Email sent'), ('EMAIL_FAILED', 'Email failed')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['category'], name='ticket_category_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['ACCOUNT_ACCESS', 'BILLING', 'BUG', 'PERFORMANCE', 'DATA', 'SECURITY', 'OTHER'])), name='ticket_category_valid'),
        ),
    ]
